#Generated by ChatGPT to demonstrate the MyMultiset_Class around 9/1/2025

#include "MyMultiset_Class.h"

int main() {
    MyMultiset_Class ms(3, 1, 2); // Length=3, values from 1 to 2

    std::cout << "Iterating from all MinValue to all MaxValue:\n";
    for (const auto& s : ms) {
        std::cout << "{ ";
        for (int val : s) {
            std::cout << val << " ";
        }
        std::cout << "}\n";
    }

    return 0;
}
